### ISSUE TITLE
Assess scaling of hybrid OpenMP/MPI

### ISSUE THREAD

**Issue by jhidding** [amrvac/AGILE-experimental#6]
- [ ] Look at Cielo & Porth et al.
- [ ] Document relevant tooling for benchmarking/profiling
- [ ] Work on diffusion example

**Comment by oporth** [comment]
In one of our weekly calls we said that while benchmarking hybrid OpenMP/MPI would be a good warmup exercise, it isn't getting us much closer to a GPU port. 
Getting acquainted with general performance profiling tools etc. is useful though.  But I don't think we want to act upon the profiling info and optimize the hybrid OpenMP/MPI .

**Comment by jhidding** [comment]
There's a difference when you talk about having a full-on "GPU port" and redirecting some of the work in an otherwise MPI/OpenMP code to the GPU. In the latter part, I would think understanding MPI performance in relation to a nested accellerator (whether it is OpenMP or OpenACC) is critical.

**Comment by oporth** [comment]
Hi Johann, 
what I mean is that I see a risk of getting side-tracked when we start optimizing the Hybrid MPI-OpenMP implementation.  OpenMP is not used in production and may contain bugs.  It would be nice to get that to work reliably but that is another project.  For this project, MPI+GPU however will most certainly be used.  So understanding MPI performance as you say is indeed very important.  

I think the line between a GPU port and 'just' redirecting work to the GPU is a bit blurry.  We might need to do some substantial changes regarding the way we pass data through the control-flow in order to have sufficient load in the kernels (e.g. going from blocks to block-packs and eventually re-ordering the arrays).  

Cheers, 
oliver
